### ISSUE TITLE
Add extra information to snippet autocomplete suggestion.

### ISSUE THREAD

**Issue by mthadley** [bryceosterhaus/atom-metal-snippets#1]
The `autocomplete-plus` package allows you to add extra information to it's suggestions, see [here](https://github.com/atom/snippets#optional-parameters).

It would be cool to have some of the snippets link to documentation or code on github. For example:
```cson
'Rendered Lifecycle':
  prefix: 'mren'
  decription: 'Render lifercycle method'
  descriptionMoreURL: 'http://metaljs.com/docs/component-lifecycle.html'
  body: """
    rendered() {
      ${1}
    }
  """
```

**Comment by bryceosterhaus** [comment]
added descriptions in https://github.com/bryceosterhaus/atom-metal-snippets/commit/ae9401fbab3fc81560cf519452da3d6b76708a52
