### ISSUE TITLE
Adds snippet for Soy classes

### ISSUE THREAD

**Issue by eduardolundgren** [bryceosterhaus/atom-metal-snippets#2]

**Comment by bryceosterhaus** [comment]
Added initial snippet here https://github.com/bryceosterhaus/atom-metal-snippets/commit/8549b658202b63306bb9f5a07192bda57fb037bd

If there are any other specific ones, we can add them to that file. For the specific closure syntax snippets, I figured users can just use a different package specifically for soy.
